-- Clear all user data from tables
TRUNCATE TABLE messages CASCADE;
TRUNCATE TABLE conversations CASCADE;
TRUNCATE TABLE request_interests CASCADE;
TRUNCATE TABLE reviews CASCADE;
TRUNCATE TABLE disputes CASCADE;
TRUNCATE TABLE deals CASCADE;
TRUNCATE TABLE requests CASCADE;
TRUNCATE TABLE user_badges CASCADE;
TRUNCATE TABLE user_roles CASCADE;
TRUNCATE TABLE profiles CASCADE;